spring.application.name=payflow


spring.datasource.url=jdbc:h2:mem:payflow;DB_CLOSE_DELAY=1
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=validate
spring.h2.console.enabled=true
